---
abstract: 'Database URIs'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Module::Build: 0.30
  Test::More: 0.88
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-db
provides:
  URI::cassandra:
    file: lib/URI/cassandra.pm
    version: 0.12
  URI::couch:
    file: lib/URI/couch.pm
    version: 0.12
  URI::couchdb:
    file: lib/URI/couchdb.pm
    version: 0.12
  URI::cubrid:
    file: lib/URI/cubrid.pm
    version: 0.12
  URI::db:
    file: lib/URI/db.pm
    version: 0.12
  URI::db2:
    file: lib/URI/db2.pm
    version: 0.12
  URI::derby:
    file: lib/URI/derby.pm
    version: 0.12
  URI::firebird:
    file: lib/URI/firebird.pm
    version: 0.12
  URI::hive:
    file: lib/URI/hive.pm
    version: 0.12
  URI::impala:
    file: lib/URI/impala.pm
    version: 0.12
  URI::informix:
    file: lib/URI/informix.pm
    version: 0.12
  URI::ingres:
    file: lib/URI/ingres.pm
    version: 0.12
  URI::interbase:
    file: lib/URI/interbase.pm
    version: 0.12
  URI::maria:
    file: lib/URI/maria.pm
    version: 0.12
  URI::mariadb:
    file: lib/URI/mariadb.pm
    version: 0.12
  URI::max:
    file: lib/URI/max.pm
    version: 0.12
  URI::maxdb:
    file: lib/URI/maxdb.pm
    version: 0.12
  URI::monet:
    file: lib/URI/monet.pm
    version: 0.12
  URI::monetdb:
    file: lib/URI/monetdb.pm
    version: 0.12
  URI::mongo:
    file: lib/URI/mongo.pm
    version: 0.12
  URI::mongodb:
    file: lib/URI/mongodb.pm
    version: 0.12
  URI::mssql:
    file: lib/URI/mssql.pm
    version: 0.12
  URI::mysql:
    file: lib/URI/mysql.pm
    version: 0.12
  URI::oracle:
    file: lib/URI/oracle.pm
    version: 0.12
  URI::pg:
    file: lib/URI/pg.pm
    version: 0.12
  URI::pgsql:
    file: lib/URI/pgsql.pm
    version: 0.12
  URI::postgres:
    file: lib/URI/postgres.pm
    version: 0.12
  URI::postgresql:
    file: lib/URI/postgresql.pm
    version: 0.12
  URI::sqlite:
    file: lib/URI/sqlite.pm
    version: 0.12
  URI::sqlite3:
    file: lib/URI/sqlite3.pm
    version: 0.12
  URI::sqlserver:
    file: lib/URI/sqlserver.pm
    version: 0.12
  URI::sybase:
    file: lib/URI/sybase.pm
    version: 0.12
  URI::teradata:
    file: lib/URI/teradata.pm
    version: 0.12
  URI::unify:
    file: lib/URI/unify.pm
    version: 0.12
  URI::vertica:
    file: lib/URI/vertica.pm
    version: 0.12
requires:
  URI: 1.40
  URI::Nested: 0.10
  perl: 5.008001
resources:
  bugtracker: https://github.com/theory/uri-db/issues/
  homepage: https://search.cpan.org/dist/URI-db/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/theory/uri-db/
version: 0.12
